# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # Run CI when a new commit is pushed
  push:
    branches:
      - main
      - dev
  # Run CI when a new pull request is created
  pull_request:
    branches:
      - main
      - dev
  # This attribute allows to manually trigger the workflow from the
  # Actions tab from the GitHub website
  workflow_dispatch:


jobs:


  # Check if the project can be built without errors
  # Linting, tests and documentation generation is allowed to fail so that in
  # case of an error in them the core build and scripts are still verified
  build:

    strategy:
      matrix:
        node-version: [19.x]
        os: [ubuntu-latest,windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (npm)
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Lint exports
      run: npm run lint:exports
      continue-on-error: true
    - name: Build
      run: npm run build
    - name: Lint circular dependencies
      run: npm run lint:circular
    - name: Create JSON schema
      run: npm run createJsonSchema
